---
title: "Top 5 causes of death"
author: "Peilin Jing, Jing Wang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction
In the past decades, the habits and preferences of people have changed as time goes by. Before the 2000s, due to the lack of productivity and low level of hygiene, a significant amount of people died from plagues and infections. When antibiotics, such as penicillin, were found in 2000 century, the fatality rate of plague and infections decreased dramatically. Because of the rapid development of modern medicine, more and more threatening diseases can now be cured. However, every coin has two sides. Technological development and the excess capacity of industry in modern society lead to a lot of new problems such as drug abuse and obesity. We are interested in doing research and analysis on the causes of death in the past ten years to see whether huge changes are occurring and remind the public that we need to pay more attention to the prevention of new deadly diseases

